### ISSUE TITLE
FloatingActionButton fab2 doasn't work 

### ISSUE THREAD

**Issue by mohamedebrahim96** [IhorKlimov/Android-Animations#2]
i'm pissed off

**Comment by IhorKlimov** [comment]
Fixed false min sdk 16 version. It's 21. Are you running it on pre L phone?

**Comment by mohamedebrahim96** [comment]
finally i fixed the error..
i use     android:src="@drawable/animated_vector_drawable"
insted of 
app:srcCompat="@drawable/animated_vector_drawable"
