### ISSUE TITLE
Not really an issue but...

### ISSUE THREAD

**Issue by bryan-ibrahim** [IhorKlimov/Android-Animations#3]
How can I return the image back to its original state or image after playing the animation.

`animatedVectorDrawable.stop()` does not work nor
`animatedVectorDrawable.reset()`

**Comment by IhorKlimov** [comment]
@bryan-ibrahim I'm not sure about which animation you're talking about, but to reset animated vector drawable, I would do this...

imageView.setImageResource(R.drawable.avd) 

after the animation is complete
